#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# confirmed working with v0.7.9
URL="http://ghost.org/zip/ghost-latest.zip"

dl $URL /usr/local/src
