#!/bin/bash -ex

###Config Vars
USER=node
# tested with 0.7.8 and 0.7.9
GHOST_URL="https://ghost.org/zip/ghost-latest.zip"
GHOST_DIR="/opt/ghost"
ZIP_TARGET="/tmp/ghost.zip"

# Get Ghost (Stable 0.7.8)
wget $GHOST_URL -O $ZIP_TARGET
unzip $ZIP_TARGET -d $GHOST_DIR/

#Set node version (0.10.40 confirmed to work); open to higher version
n 0.10.40

# based on basic documented install
chown -R $USER:$USER $GHOST_DIR
cd $GHOST_DIR && su -c "npm install --production" $USER

#ghost runs on 2368. Proxy to port 80 and port 443 (SSL/TLS)
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost

#Creates current db
cd $GHOST_DIR && su -c "nohup npm start --production &" $USER
cd $GHOST_DIR && su -c "npm stop" $USER


# pm2
cd $GHOST_DIR && su -c "NODE_ENV=production pm2 start --name 'ghost' index.js; pm2 dump" $USER


# remove conflicting nginx site (web-control)
rm /etc/nginx/sites-enabled/nodejs
rm $ZIP_TARGET

# to validate URL
pip install validators
