#!/bin/bash -ex

#Config Vars
GHOST_URL="https://ghost.org/zip/ghost-0.7.8.zip"
GHOST_DIR="/opt/ghost/"


# Get Ghost (Stable 0.7.8)
wget $GHOST_URL -O /tmp/ghost.zip
unzip /tmp/ghost.zip -d $GHOST_DIR

#Set node version (0.10.40 confirmed to work)
cd $GHOST_DIR && /usr/local/bin/npm install --production
mv /tmp/ghost-dev.db $GHOST_DIR/content/data/ghost.db

#nginx considerations
#ghost runs on 2368. Proxy to port 80 and port 443 (SSL/TLS)
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost


chown -R node:node $GHOST_DIR

# pm2
cd $GHOST_DIR && /usr/local/bin/pm2 start index.js --name Ghost --env production
rm /etc/nginx/sites-enabled/ghost


