#!/bin/bash -ex

###Config Vars
USER=node
INSTALL_DIR="/opt/ghost"
SRC="/usr/local/src/ghost-latest.zip"

unzip $SRC -d $INSTALL_DIR/
rm $SRC

#Set node version (0.10.40 confirmed to work); open to higher version
n 0.10.40

# based on basic documented install
chown -R $USER:$USER $INSTALL_DIR
cd $INSTALL_DIR && su -c "npm install --production" $USER

#ghost runs on 2368. Proxy to port 80 and port 443 (SSL/TLS)
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost
rm /etc/nginx/sites-enabled/nodejs

#Creates current db
cd $INSTALL_DIR && su -c "nohup npm start --production &" $USER
cd $INSTALL_DIR && su -c "npm stop" $USER

# pm2
cd $INSTALL_DIR && su -c "NODE_ENV=production pm2 start --name 'ghost' index.js; pm2 dump" $USER

# configure ghost to use postfix
CONF="/opt/ghost/config.js"
TAB2="\n        "
TAB3="$TAB2    "
TAB4="$TAB3    "
OLD="mail: {},"
NEW="mail: {${TAB3}transport: 'SMTP',${TAB3}options: {${TAB4}service: 'sendmail',${TAB3}}${TAB2}},"
sed -i "s|$OLD|$NEW|" $CONF

# to validate URL
pip install validators

