#!/bin/bash -ex

###Config Vars
USER=node
INSTALL_DIR="/opt/ghost"
SRC="/usr/local/src/ghost-latest.zip"

#Set node version (6.9.0 confirmed to work); open to higher version
n 6.9.0

# based on basic documented install
mkdir $INSTALL_DIR
chown -R $USER:$USER $INSTALL_DIR
cd $INSTALL_DIR
npm i -g ghost-cli
ghost install local
ghost stop

#ghost runs on 2368. Proxy to port 80 and port 443 (SSL/TLS)
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost

systemctl enable ghost_blog

# configure ghost to use postfix
CONF="$INSTALL_DIR/config.development.json"
OLD='"transport": "Direct"'
NEW='"transport": "sendmail"'
while [ ! -f $CONF ]; do
   sleep 2
done
sed -i "s|$OLD|$NEW|" $CONF