#!/bin/bash -e
# initialize Ghost

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

if [ -z "$APP_UNAME" ]; then
    if [ -n "$APP_PASS" ] && [ -n "$APP_EMAIL" ] && [ -n "$APP_DOMAIN" ]; then
        APP_UNAME="DEFAULT"
    fi
fi

$INITHOOKS_PATH/bin/ghost.py --pass="$APP_PASS" --uname="$APP_UNAME" --email="$APP_EMAIL" --domain="$APP_DOMAIN"
